### PR TITLE
test: adding tests cases.

### PR DESCRIPTION
**Pull request by awais786**
1. Adding tests

@salman2013 initiated this [PR](https://github.com/salman2013/DoneXBlock/pull/1) . I Just cherrypick his effort here.

### CODE REVIEW

**Comment by feanil** [comment]
@awais786 is this ready for review?

**Comment by awais786** [comment]
@feanil sorry for late reply. This PR is in internal review. After internal review i will tag you.

**Comment by OmarIthawi** [comment]
@awais786 Would you mind taking a look at the other PR here I've done few years ago on the other fork of DoneXBlock:
 
 - https://github.com/openedx/DoneXBlock/pull/125

Please let me know if you have any questions.

**Comment by awais786** [comment]
@OmarIthawi please share your PR.

**Comment by OmarIthawi** [comment]
> @OmarIthawi please share your PR.

Pardon. I shared the wrong link. Here you go @awais786: https://github.com/pmitros/DoneXBlock/pull/21/files

**Comment by feanil** [comment]
@awais786 I'm gonna convert this to a draft PR until it is ready for public review and merging.

**Comment by feanil** [comment]
@awais786 this has been in Draft for a month, are you still working on it?

**Comment by awais786** [comment]
@feanil I will start working on this tomorrow and try to finish it.

**Pull request closed without merging**
